import { PhotoData, CityData, UserProfile, ReactionCounts, EmojiType } from './types';

const gradients = [
  'from-yellow-600 to-red-600',
  'from-blue-600 to-purple-600',
  'from-green-600 to-teal-600',
  'from-pink-600 to-red-600',
  'from-orange-600 to-yellow-600',
  'from-indigo-600 to-blue-600',
  'from-cyan-600 to-blue-600',
  'from-purple-600 to-pink-600',
  'from-emerald-600 to-green-600',
  'from-amber-600 to-orange-600',
];

export const mockPhotos: PhotoData[] = [
  {
    id: '1',
    gradient: gradients[0],
    city: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    timeAgo: '2m ago',
    reactions: { '❤️': 342, '😮': 89, '😂': 156, '🌍': 234, '🙏': 67 },
    userReaction: null,
    createdAt: new Date(Date.now() - 2 * 60000),
  },
  {
    id: '2',
    gradient: gradients[1],
    city: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    timeAgo: '14m ago',
    reactions: { '❤️': 456, '😮': 123, '😂': 234, '🌍': 345, '🙏': 89 },
    userReaction: null,
    createdAt: new Date(Date.now() - 14 * 60000),
  },
  {
    id: '3',
    gradient: gradients[2],
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    timeAgo: '31m ago',
    reactions: { '❤️': 612, '😮': 198, '😂': 423, '🌍': 567, '🙏': 145 },
    userReaction: null,
    createdAt: new Date(Date.now() - 31 * 60000),
  },
  {
    id: '4',
    gradient: gradients[3],
    city: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    timeAgo: '47m ago',
    reactions: { '❤️': 378, '😮': 156, '😂': 289, '🌍': 412, '🙏': 102 },
    userReaction: null,
    createdAt: new Date(Date.now() - 47 * 60000),
  },
  {
    id: '5',
    gradient: gradients[4],
    city: 'New York',
    country: 'United States',
    countryCode: 'US',
    timeAgo: '1h ago',
    reactions: { '❤️': 523, '😮': 201, '😂': 367, '🌍': 489, '🙏': 134 },
    userReaction: null,
    createdAt: new Date(Date.now() - 60 * 60000),
  },
  {
    id: '6',
    gradient: gradients[5],
    city: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    timeAgo: '1h ago',
    reactions: { '❤️': 687, '😮': 289, '😂': 456, '🌍': 723, '🙏': 201 },
    userReaction: null,
    createdAt: new Date(Date.now() - 62 * 60000),
  },
  {
    id: '7',
    gradient: gradients[6],
    city: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    timeAgo: '1h ago',
    reactions: { '❤️': 445, '😮': 167, '😂': 298, '🌍': 401, '🙏': 112 },
    userReaction: null,
    createdAt: new Date(Date.now() - 65 * 60000),
  },
  {
    id: '8',
    gradient: gradients[7],
    city: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    timeAgo: '2h ago',
    reactions: { '❤️': 534, '😮': 178, '😂': 312, '🌍': 456, '🙏': 123 },
    userReaction: null,
    createdAt: new Date(Date.now() - 120 * 60000),
  },
  {
    id: '9',
    gradient: gradients[8],
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    timeAgo: '2h ago',
    reactions: { '❤️': 401, '😮': 145, '😂': 267, '🌍': 378, '🙏': 98 },
    userReaction: null,
    createdAt: new Date(Date.now() - 125 * 60000),
  },
  {
    id: '10',
    gradient: gradients[9],
    city: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    timeAgo: '2h ago',
    reactions: { '❤️': 567, '😮': 212, '😂': 389, '🌍': 501, '🙏': 156 },
    userReaction: null,
    createdAt: new Date(Date.now() - 130 * 60000),
  },
  {
    id: '11',
    gradient: gradients[0],
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    timeAgo: '3h ago',
    reactions: { '❤️': 612, '😮': 267, '😂': 445, '🌍': 567, '🙏': 178 },
    userReaction: null,
    createdAt: new Date(Date.now() - 180 * 60000),
  },
  {
    id: '12',
    gradient: gradients[1],
    city: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    timeAgo: '3h ago',
    reactions: { '❤️': 489, '😮': 189, '😂': 334, '🌍': 423, '🙏': 134 },
    userReaction: null,
    createdAt: new Date(Date.now() - 185 * 60000),
  },
];

export const mockCities: CityData[] = [
  { name: 'Istanbul', countryCode: 'TR', emoji: '🇹🇷', momentCount: 342, lat: 41.0082, lng: 28.9784, activityLevel: 'hot' },
  { name: 'Lagos', countryCode: 'NG', emoji: '🇳🇬', momentCount: 289, lat: 6.5244, lng: 3.3792, activityLevel: 'hot' },
  { name: 'Tokyo', countryCode: 'JP', emoji: '🇯🇵', momentCount: 612, lat: 35.6762, lng: 139.6503, activityLevel: 'hot' },
  { name: 'São Paulo', countryCode: 'BR', emoji: '🇧🇷', momentCount: 378, lat: -23.5505, lng: -46.6333, activityLevel: 'warm' },
  { name: 'New York', countryCode: 'US', emoji: '🇺🇸', momentCount: 523, lat: 40.7128, lng: -74.006, activityLevel: 'hot' },
  { name: 'Mumbai', countryCode: 'IN', emoji: '🇮🇳', momentCount: 687, lat: 19.0760, lng: 72.8777, activityLevel: 'hot' },
  { name: 'London', countryCode: 'GB', emoji: '🇬🇧', momentCount: 445, lat: 51.5074, lng: -0.1278, activityLevel: 'warm' },
];

export const mockUserProfile: UserProfile = {
  id: 'user-123',
  city: 'Istanbul',
  country: 'Turkey',
  countryCode: 'TR',
  anonymous: true,
  streak: 47,
  momentsCaptured: 184,
  reactionsReceived: 12847,
  isPremium: false,
  joinedDate: new Date(Date.now() - 365 * 24 * 60 * 60000),
};

export const premiumStats = {
  momentCount: 2847,
  activeCountries: 47,
  activeCities: 891,
};

export const archivePhotos: PhotoData[] = mockPhotos.slice(0, 30).map((photo, i) => ({
  ...photo,
  id: `archive-${i}`,
}));
